Resources
{
	"materials/hud/leaderboard_class_demo_clusterbomb.vmt"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vtf"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb_giant.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vmt"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon.vtf"	"file"
	"materials/hud/leaderboard_class_demo_loosecannon_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_burst.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_burst.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_burst_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf_giant.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_huntsman_bleed.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_huntsman_bleed.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_huntsman_bleed_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_stun.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_stun.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_stun_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_stun_spammer.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_stun_spammer.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_stun_spammer_giant.vmt"	"file"
}