Resources
{
	"materials/hud/leaderboard_class_random_lite.vmt"	"file"
	"materials/hud/leaderboard_class_random_lite.vtf"	"file"
	"materials/hud/leaderboard_class_random_lite_giant.vmt"	"file"
	"materials/hud/leaderboard_class_random_lite_giant.vtf"	"file"
	"materials/hud/leaderboard_class_tank_sticky_hellmet.vmt"	"file"
	"materials/hud/leaderboard_class_tank_sticky_hellmet.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_scorch.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_scorch.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_backup.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_backup.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_hyper.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_hyper.vtf"	"file"
	"materials/hud/leaderboard_class_medic_soldier_barrage.vtf"	"file"
	"materials/hud/leaderboard_class_medic_soldier_barrage.vmt"	"file"
	"materials/models/props_frontline/tank_beige.vmt"	"file"
	"materials/models/props_frontline/tank_beige.vtf"	"file"
	"materials/models/props_frontline/tank_blue.vmt"	"file"
	"materials/models/props_frontline/tank_blue.vtf"	"file"
	"materials/models/props_frontline/tank_green.vmt"	"file"
	"materials/models/props_frontline/tank_green.vtf"	"file"
	"materials/models/props_frontline/tank_lights_off.vmt"	"file"
	"materials/models/props_frontline/tank_lights_on.vmt"	"file"
	"materials/models/props_frontline/tank_red.vmt"	"file"
	"materials/models/props_frontline/tank_red.vtf"	"file"
	"models/props_frontline/tank_turret.dx80.vtx"	"file"
	"models/props_frontline/tank_turret.dx90.vtx"	"file"
	"models/props_frontline/tank_turret.mdl"	"file"
	"models/props_frontline/tank_turret.phy"	"file"
	"models/props_frontline/tank_turret.vvd"	"file"
}