name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the static site
      - name: Build site
        run: npm run build

      # 5️⃣ Show disk usage before cleanup (optional)
      - name: Check disk usage before cleanup
        run: |
          df -h
          du -h --max-depth=2 | sort -hr | head -n 20

      # 6️⃣ Clean up temporary files to free space
      - name: Clean build caches
        run: |
          echo "Removing temporary build files to prevent disk full..."
          rm -rf node_modules .cache build dist .next

      # 7️⃣ Show disk usage after cleanup (optional)
      - name: Check disk usage after cleanup
        run: df -h

      # 8️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # This directory should contain your final built static site
          publish_dir: ./public
